import { type CSSProperties } from 'react';

export const ContactStyle: Record<string, CSSProperties> = {
    container: {
        display: "flex",
        width: "100%",
        maxWidth: "1100px",
        margin: "0 auto",
        minHeight: "600px",
        borderRadius: "16px",
        overflow: "hidden",
        boxShadow: "var(--shadow)",
        border: "1px solid var(--border)",
        background: "var(--bg)",
        transition: "all 0.3s ease",
    },
    leftPanel: {
        background: "linear-gradient(135deg, #1e3a8a 0%, #0f172a 100%)",
        width: "40%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        padding: "48px 40px",
        boxSizing: "border-box",
        textAlign: "left",
    },
    leftTop: {
        display: "flex",
        flexDirection: "column",
    },
    heading: {
        color: "#ffffff",
        fontWeight: 600,
        fontSize: "30px",
        lineHeight: 1.25,
        margin: 0,
        fontFamily: "var(--heading)",
    },
    subheading: {
        color: "#94a3b8",
        fontSize: "14px",
        lineHeight: 1.6,
        fontWeight: 400,
        margin: "16px 0 0 0",
    },
    infoList: {
        display: "flex",
        flexDirection: "column",
        gap: "24px",
        marginTop: "40px",
    },
    infoItem: {
        display: "flex",
        flexDirection: "column",
        gap: "4px",
    },
    infoLabel: {
        fontSize: "11px",
        color: "#64748b",
        textTransform: "uppercase",
        letterSpacing: "1.2px",
        fontWeight: 600,
        margin: 0,
    },
    infoValue: {
        fontSize: "15px",
        color: "#f1f5f9",
        textDecoration: "none",
        fontWeight: 400,
        transition: "color 0.2s ease",
    },
    socialLinks: {
        display: "flex",
        gap: "16px",
        marginTop: "40px",
        borderTop: "1px solid rgba(255, 255, 255, 0.08)",
        paddingTop: "24px",
    },
    socialLink: {
        color: "#94a3b8",
        fontSize: "14px",
        textDecoration: "none",
        transition: "color 0.2s ease",
        fontWeight: 500,
    },
    rightPanel: {
        flex: 1,
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: "48px 60px",
        boxSizing: "border-box",
        background: "var(--bg)",
        gap: "8px",
        textAlign: "left",
    },
    inputTitle: {
        color: "var(--text-h)",
        fontSize: "14px",
        fontWeight: 500,
    },
    errorText: {
        color: "#ef4444",
        fontSize: "12px",
        marginTop: "-12px",
        marginBottom: "8px",
        display: "block",
    },
    buttonBase: {
        marginTop: "20px",
        padding: "14px",
        color: "#ffffff",
        border: "none",
        borderRadius: "8px",
        fontSize: "15px",
        cursor: "pointer",
        fontWeight: 500,
        letterSpacing: "0.3px",
        transition: "all 0.2s ease",
        width: "100%",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
    }
};