import { type CSSProperties } from 'react';

// Refined Slate tokens (light-mode)
const t = {
    ink:         'oklch(14% 0.015 260)',
    inkMid:      'oklch(42% 0.012 255)',
    inkMuted:    'oklch(66% 0.008 255)',
    paper:       'oklch(98.5% 0.005 250)',
    paperSubtle: 'oklch(96.5% 0.008 250)',
    paperCard:   'oklch(100% 0 0)',
    accent:      'oklch(52% 0.18 265)',
    accentLight: 'oklch(52% 0.18 265 / 0.08)',
    accentMid:   'oklch(52% 0.18 265 / 0.20)',
    rule:        'oklch(90% 0.01 250)',
    shadow:      '0 2px 12px oklch(0% 0 0 / 0.06)',
    fontSans:    "'Inter', system-ui, -apple-system, sans-serif",
};

export const styles = {
    container: {
        marginBottom: '0',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'stretch',
        width: '100%',
    } as CSSProperties,

    questionWrapper: {
        display: 'flex',
        justifyContent: 'flex-start',
        width: '100%',
    } as CSSProperties,

    questionButton: {
        padding: 'clamp(16px, 2vw, 20px) clamp(18px, 3vw, 24px)',
        borderRadius: '16px',
        border: `1px solid ${t.accentLight}`,
        backgroundColor: t.paperCard,
        color: t.ink,
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '16px',
        fontSize: 'clamp(14px, 1.5vw, 15px)',
        fontWeight: 600,
        lineHeight: '1.5',
        textAlign: 'left',
        width: '100%',
        transition: 'background-color 0.20s ease, border-color 0.20s ease, transform 0.20s ease',
        fontFamily: t.fontSans,
        boxShadow: '0 20px 60px oklch(0% 0 0 / 0.05)',
    } as CSSProperties,

    iconWrapper: (isOpen: boolean): CSSProperties => ({
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: '26px',
        width: '26px',
        height: '26px',
        borderRadius: '50%',
        border: `1.6px solid ${isOpen ? t.accent : t.inkMuted}`,
        color: isOpen ? t.accent : t.inkMuted,
        backgroundColor: isOpen ? 'rgba(71, 85, 255, 0.08)' : 'transparent',
        fontSize: '18px',
        lineHeight: 1,
        flexShrink: 0,
        transition: 'transform 0.25s ease, border-color 0.25s ease, color 0.25s ease, background-color 0.25s ease',
        transform: isOpen ? 'rotate(45deg)' : 'rotate(0deg)',
    }),

    answerWrapper: (isOpen: boolean): CSSProperties => ({
        display: 'flex',
        justifyContent: 'flex-end',
        marginTop: isOpen ? '10px' : '0px',
        maxHeight: isOpen ? '600px' : '0px',
        opacity: isOpen ? 1 : 0,
        overflow: 'hidden',
        width: '100%',
        transition: 'max-height 0.38s ease, opacity 0.3s ease, margin-top 0.25s ease',
    }),

    answerBubble: {
        padding: '18px 24px',
        backgroundColor: 'rgba(71, 85, 255, 0.08)',
        border: `1px solid rgba(71, 85, 255, 0.16)`,
        color: t.inkMid,
        borderRadius: '16px',
        width: 'min(100%, 680px)',
        maxWidth: '92%',
        alignSelf: 'flex-end',
        fontSize: 'clamp(14px, 1.2vw, 15px)',
        lineHeight: '1.8',
        fontWeight: 400,
        fontFamily: t.fontSans,
        boxShadow: '0 24px 50px oklch(0% 0 0 / 0.04)',
        backdropFilter: 'blur(8px)',
    } as CSSProperties,
};
